
services:
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  
volumes:
  redis_data:

  